### PR TITLE
replaced freenode with libera.chat

### PR DESCRIPTION
**Pull request by bernes1**

### CODE REVIEW

**Review by stigok — APPROVED** [review]

**Comment by stigok** [comment]
Did you check if the local copy of the repository running on the Pi has a diff? There might be other changes there that could be nice to push up here :)

**Comment by bernes1** [comment]
i did not check on the pi since I don't have ssh access to log in to the pi. can you ssh into the pi and check?

**Comment by stigtsp** [comment]
the irc bot needs to connect over tls to access #oslohackerspace btw... after we moved to libera

**Comment by stigok** [comment]
> the irc bot needs to connect over tls to access #oslohackerspace btw... after we moved to libera

Right, so this is probably one of these things that needs to get synced :)

**Comment by stigtsp** [comment]
i foresee a merge conflict in the future :crystal_ball: :mage: :smile:

**Pull request merged**
